### ISSUE TITLE
Play, Repair, and Check for Updates doesn't work after changing DCS directory folder name 

### ISSUE THREAD

**Issue by Tuuvas** [jeffboulanger/DCS-Alternative-Launcher#12]
![AltLauncher_ChangeDirectoryName_Short](https://user-images.githubusercontent.com/34009225/61999786-6f868c00-b07d-11e9-9602-2ebd230541ea.gif)

**Comment by jeffboulanger** [comment]
Already made a change, you should see an error in the next version.   However, I will leave this open to add more user friendly messages and try to detect the crash that will probably occur first.

**Comment by Tuuvas** [comment]
Confirmed error is now seen:
![image](https://user-images.githubusercontent.com/34009225/62000405-d9596280-b08a-11e9-947f-320d83a854b4.png)
