### ISSUE TITLE
Overlay on YouTube video causes lag/audio-video desync

### ISSUE THREAD

**Issue by Tuuvas** [jeffboulanger/DCS-Alternative-Launcher#14]
Attempting to manipulate the YouTube overlay functions (ex. Play/Pause, Volume, etc) causes video lag and results in desync'd audio.  Unfortunately I can't attach .mp4 files to demonstrate...

**Comment by jeffboulanger** [comment]
need to try 

CefSettings s = new CefSettings();
s.SetOffScreenRenderingBestPerformanceArgs();
Cef.Initialize(s);
