### ISSUE TITLE
"No Template Defined" blocks the creation of a Viewport set

### ISSUE THREAD

**Issue by asherao** [jeffboulanger/DCS-Alternative-Launcher#42]
When attempting to make a viewport for an aircraft that does not have a default template, the options that become available are "Save" and "Cancel". Clicking either option closes the wizard and does not make a viewport set. 
Trace Log attached. 
[trace.log](https://github.com/jeffboulanger/DCS-Alternative-Launcher/files/3562292/trace.log)
Gif attached
![DAL_Issue002](https://user-images.githubusercontent.com/15984377/64062188-9573f300-cc1e-11e9-8569-3942dce0e9fa.gif)
DAL Version: 0.15.7181.42496

**Comment by jeffboulanger** [comment]
This is technically valid.   Without a template that message should show, and the editor should then show after, however, the issue in this case is that there are no known viewports for the F-14 in DAL atm... so not a bug, but more i havent gotten around to adding the default viewports yet for the F-14.. maybe the better thing to do would be to not show any module in the drop down if there are no defined viewports.

**Comment by asherao** [comment]
The 5 HB supported Viewports for the F14:
-F14_DDD init is located in C:\Games\DCS World OpenBeta\Mods\aircraft\F14\Cockpit\Scripts\DetailDataDisplay\Indicator\init.lua

-F14_TID init is located in C:\Games\DCS World OpenBeta\Mods\aircraft\F14\Cockpit\Scripts\TacticalInformationDisplay\Indicator\init.lua

-F14_VDI init is located in C:\Games\DCS World OpenBeta\Mods\aircraft\F14\Cockpit\Scripts\VerticalDisplayIndicator\Indicator\init.lua

-F14_HSD init is located in C:\Games\DCS World OpenBeta\Mods\aircraft\F14\Cockpit\Scripts\HorizontalSituationDisplay\Indicator\init.lua

-F14_JESTER_MENU init is located in C:\Games\DCS World OpenBeta\Mods\aircraft\F14\Cockpit\Scripts\JesterAI

Unsupported Viewports:
F14_VHF_ARC182 - already defined as is. Unknown dimensions.
F14_UHF_ARC159 - already defined as is. Unknown dimensions.
F14_RWR_PILOT - custom made. Unknown dimensions.
F14_RWR_RIO - custom made. Unknown dimensions.
F14_FreqChart - custom made. Unknown dimensions.
F14_VideoExport - Did not work.
ICS - Did not work.
HUD - Did not work.
EMCD - Did not work.

[F14CustomViewports.zip](https://github.com/jeffboulanger/DCS-Alternative-Launcher/files/3569793/F14CustomViewports.zip)
~Bailey

**Comment by jeffboulanger** [comment]
You can edit viewports when a module is defined to having viewports to edit... so this should be non-existent now.
